name: test github action

on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: set up node
        uses: action/setup-node@v1
        with:
          node-version: '16.x'
      
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Make Directory for results
        run: mkdir -p testResults

      - name: run POSTMAN Collection
        run: |
         newman run Projet 1 - API GitHub V3.postman_collection.json -e Test Project 1.postman_environment.json -r ci,htmlextra
      
      - name: Output the run Details
        uses: actions/upload-artifacts@v2
        with:
         name: RunReports
         path: testResults



